### ISSUE TITLE
Oracle-xe test resource provider crashes when used together with other test-resources

### ISSUE THREAD

**Issue by mryan43** [micronaut-projects/micronaut-test-resources#174]
I'm writing an application that uses oracle-xe and wiremock in its tests.

My application-test.yml file looks like this : 

```yml
test-resources:
  containers:
    extservice:
      image-name: wiremock:2.32.0
      ro-fs-bind:
        - wiremock: /home/wiremock
      hostnames:
        - extservice.hostname
      exposed-ports:
        - extservice.port: 8080
    oracle:
      image-name: oracle-xe:21-slim-faststart
      ro-fs-bind:
        - oracle/init: /container-entrypoint-initdb.d
datasources:
  default:
    db-type: oracle 
```

When my app tries to resolve the "extservice.hostname" property, the test resource server crashes like this : 

```
16:48:31.428 [default-nioEventLoopGroup-1-6] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: begin 0, end -1, length 8
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 8
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at io.micronaut.testresources.jdbc.AbstractJdbcTestResourceProvider.datasourceNameFrom(AbstractJdbcTestResourceProvider.java:154)
	at io.micronaut.testresources.oracle.xe.OracleXETestResourceProvider.getRequiredProperties(OracleXETestResourceProvider.java:36)
	at io.micronaut.testresources.server.TestResourcesController.lambda$getRequiredProperties$2(TestResourcesController.java:66)
```

It looks like OracleXETestResourceProvider calls datasourceNameFrom on the "extservice.hostname" property, which is not very wise.

**Comment by melix** [comment]
This is fixed in 1.2.4, this should have been closed earlier, sorry.
