### ISSUE TITLE
Mongo test resource does not work

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-test-resources#316]
### Expected Behavior

I tried to upgrade my micronaut mongo example to 4.0 and use test-resouce instead of test containers.

Failed when running tests.

### Actual Behaviour

```bash
Error instantiating bean of type  [com.mongodb.MongoClientSettings]

Message: Could not resolve placeholder ${auto.test.resources.mongodb.uri}
Path Taken: new DefaultMongoRepositoryOperations(String serverName,BeanContext beanContext,DateTimeProvider dateTimeProvider,RuntimeEntityRegistry runtimeEntityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,MongoClient mongoClient,MongoCollectionNameProvider collectionNameProvider,ExecutorService executorService) --> new DefaultMongoRepositoryOperations(String serverName,BeanContext beanContext,DateTimeProvider dateTimeProvider,RuntimeEntityRegistry runtimeEntityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,[MongoClient mongoClient],MongoCollectionNameProvider collectionNameProvider,ExecutorService executorService) --> DefaultMongoClientFactory.mongoClient([MongoClientSettings settings]) --> DefaultMongoClientSettingsFactory.mongoClientSettings([DefaultMongoConfiguration mongoConfiguration])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.mongodb.MongoClientSettings]

Message: Could not resolve placeholder ${auto.test.resources.mongodb.uri}
Path Taken: new DefaultMongoRepositoryOperations(String serverName,BeanContext beanContext,DateTimeProvider dateTimeProvider,RuntimeEntityRegistry runtimeEntityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,MongoClient mongoClient,MongoCollectionNameProvider collectionNameProvider,ExecutorService executorService) --> new DefaultMongoRepositoryOperations(String serverName,BeanContext beanContext,DateTimeProvider dateTimeProvider,RuntimeEntityRegistry runtimeEntityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,[MongoClient mongoClient],MongoCollectionNameProvider collectionNameProvider,ExecutorService executorService) --> DefaultMongoClientFactory.mongoClient([MongoClientSettings settings]) --> DefaultMongoClientSettingsFactory.mongoClientSettings([DefaultMongoConfiguration mongoConfiguration])
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2322)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
	at app//io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
	at app//io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
	at app//io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
	at app//io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2164)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1326)
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
	at app//io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
	at app//io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
	at app//io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
	at app//io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2164)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1326)
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
	at app//io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
	at app//io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
	at app//io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
	at app//io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2164)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1326)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.instantiate(AbstractInitializableBeanDefinition.java:772)
	at app//io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:156)
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
	at app//io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
	at app//io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
	at app//io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
	at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:840)
	at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:832)
	at app//io.micronaut.data.runtime.operations.DefaultRepositoryOperationsRegistry.provide(DefaultRepositoryOperationsRegistry.java:53)
	at app//io.micronaut.data.runtime.intercept.DataInterceptorResolver.findInterceptor(DataInterceptorResolver.java:113)
	at app//io.micronaut.data.runtime.intercept.DataInterceptorResolver.lambda$resolve$2(DataInterceptorResolver.java:94)
	at java.base@17.0.6/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at app//io.micronaut.data.runtime.intercept.DataInterceptorResolver.resolve(DataInterceptorResolver.java:73)
	at app//io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at app//com.example.CustomerRepositorySpec.setup(CustomerRepositorySpec.groovy:41)
Caused by: io.micronaut.context.exceptions.ConfigurationException: Could not resolve placeholder ${auto.test.resources.mongodb.uri}
	at app//io.micronaut.context.env.DefaultPropertyPlaceholderResolver$PlaceholderSegment.getValue(DefaultPropertyPlaceholderResolver.java:310)
	at app//io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholdersObject(DefaultPropertyPlaceholderResolver.java:111)
	at app//io.micronaut.context.env.PropertySourcePropertyResolver.resolvePlaceHoldersIfNecessary(PropertySourcePropertyResolver.java:799)
	at app//io.micronaut.context.env.PropertySourcePropertyResolver.getProperty(PropertySourcePropertyResolver.java:393)
	at app//io.micronaut.context.DefaultApplicationContext.getProperty(DefaultApplicationContext.java:219)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.resolvePropertyValue(AbstractInitializableBeanDefinition.java:2107)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.getPropertyValueForSetter(AbstractInitializableBeanDefinition.java:1074)
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	... 56 more

````

### Environment Information

Windows 10 Pro, Java 17

### Example Application

https://github.com/hantsy/micronaut-sandbox/tree/master/data-mongodb-groovy

### Version

4.0.0-M3

**Comment by hantsy** [comment]
Another example upgraded to 4.0 and used test-resource, got the same result.

https://github.com/hantsy/micronaut-sandbox/tree/master/mongodb-album-service

**Comment by melix** [comment]
I just checked your branch, re-applied the test resources plugin which was commented out, removed the test containers dependencies, and removed the hardcoded URL in the application.yml property and it seems to work properly. I have a test failing which seems unrelated to test-resources:

https://scans.gradle.com/s/vtu67yltpyyj4/tests/:test/com.example.ApplicationSpec/get%20all%20customers?top-execution=1

**Comment by hantsy** [comment]
yes, the newest codes, I tried to remove test-resources and testcontainers.

**Comment by alvarosanchez** [comment]
Thanks for the report. I re-reviewed this issue and I’m closing it as `cannot reproduce` based on both the historical thread and a fresh verification pass.

What I found:

- This issue was originally filed against `4.0.0-M3` on June 10, 2023, but it did not include concrete reproduction steps.
- On June 19, 2023, a maintainer checked the linked sample and reported that it worked after re-applying the Micronaut test-resources plugin, removing the Testcontainers dependencies, and removing the hardcoded MongoDB URL from `application.yml`.
- On April 22, 2026, I reran the current MongoDB smoke test from this repository with:
  `./gradlew :micronaut-test-resources-mongodb:test --tests io.micronaut.testresources.mongodb.MongoDBStartedTest`
  That test passed and started a real MongoDB container successfully.
- The current MongoDB provider still resolves `mongodb.uri` (and `mongodb.servers.<name>.uri`). The `auto.test.resources.*` form is the lazy placeholder generated by test resources internally; if `auto.test.resources.mongodb.uri` remains unresolved in an application, that points to the test-resources resolver not being active in that build/configuration.

Given the maintainer’s earlier non-reproducer, the lack of a minimal reproducer in the original report, and the current passing MongoDB verification in this repository, there isn’t enough evidence of an active defect in Micronaut Test Resources itself.

If you can still reproduce this on a current supported version, please open a new issue with a minimal sample and include the exact Micronaut, Micronaut Data, and Micronaut Test Resources versions plus the relevant MongoDB/test-resources configuration.

---
###### ✨ This message was AI-generated using gpt-5.4
