### ISSUE TITLE
Test Resources do not work with Redis

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-test-resources#389]
### Expected Behavior

When I create a Micronaut application like this:

```
mn create-app example.micronaut.test-resources-redis-fail-no-aot --build=gradle_kotlin --features=test-resources,redis-lettuce
```

... and:

1. Comment out `redis.uri` in `application.properties`.
2. Comment out the `aot` plugin from build.gradle.kts.
3. Add a test using a `StatefulRedisConnection` from Lettuce.

I expect the application to be able to build with `./gradlew build --info` and the test to be able to connect to Redis.

### Actual Behaviour

I get the error below every time when building. If I set the Test Resources setting `sharedServer` to true, the build fails the first time and afterwards succeeds due to Redis already being running from the previous build.

It seems Test Resources are not able to detect correctly, when the Redis container has actually started up, so it tries to run the test before the container is running and therefore get a connection refused, when attempting to connect to it.

The port number it tries to connect on is correct.

Error:

```
RedisTest > testRedis() FAILED
    org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [io.lettuce.core.api.StatefulRedisConnection<java.lang.String, java.lang.String> redisConnection] in constructor [public example.micronaut.RedisTest(io.lettuce.core.api.StatefulRedisConnection<java.lang.String, java.lang.String>)]: Error instantiating bean of type  [io.lettuce.core.api.StatefulRedisConnection]

    Message: Unable to connect to localhost/<unresolved>:32817
    Path Taken: DefaultRedisClientFactory.redisConnection(RedisClient redisClient)
        at java.base@17.0.8.1/java.util.Optional.orElseGet(Optional.java:364)
        at java.base@17.0.8.1/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base@17.0.8.1/java.util.ArrayList.forEach(ArrayList.java:1511)

        Caused by:
        io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.lettuce.core.api.StatefulRedisConnection]

        Message: Unable to connect to localhost/<unresolved>:32817
        Path Taken: DefaultRedisClientFactory.redisConnection(RedisClient redisClient)
            at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2322)
            at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
            at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
            at app//io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
            at app//io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
            at app//io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
            at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
            at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
            at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
            at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:840)
            at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension.resolveParameter(MicronautJunit5Extension.java:380)
            ... 3 more

            Caused by:
            io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:32817
                at app//io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
                at app//io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
                at app//io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:350)
                at app//io.lettuce.core.RedisClient.connect(RedisClient.java:216)
                at app//io.micronaut.configuration.lettuce.AbstractRedisClientFactory.redisConnection(AbstractRedisClientFactory.java:88)
                at app//io.micronaut.configuration.lettuce.DefaultRedisClientFactory.redisConnection(DefaultRedisClientFactory.java:68)
                at app//io.micronaut.configuration.lettuce.$DefaultRedisClientFactory$RedisConnection1$Definition.instantiate(Unknown Source)
                at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
                ... 13 more

                Caused by:
                io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:32817

                    Caused by:
                    java.net.ConnectException: Connection refused
                        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
                        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
                        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
                        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
                        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
                        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
                        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
                        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
                        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps To Reproduce

1. Clone `https://github.com/runenielsen/test-resources-redis-fail-no-aot`.
2. Run `./gradlew build --info`.
3. See that the build fails with the error above.
4. Change the line `testResources { sharedServer = false }` to `testResources { sharedServer = true }` in `build.gradle.kts`
5. Run `./gradlew build --info`.
6. See that the build fails with the error above.
7. Run `./gradlew build --info` again.
8. See that the build now succeeds, because Redis was started in the previous build.

### Environment Information

OS: MacOS Ventura 13.5.2
JDK: OpenJDK Temurin 17.0.8.1
Docker installed via Rancher Desktop 1.9.1

### Example Application

https://github.com/runenielsen/test-resources-redis-fail-no-aot

### Version

4.1.0

**Comment by runenielsen** [comment]
I also tried to add this in `test/resources/application.properties` -  it doesn't help:

```
test-resources.containers.redis.wait-strategy.log.regex=.*Ready to accept connections.*
```

It is picked up correctly, because if I change it to something that doesn't occur in the Redis container log, the test times out.
