### ISSUE TITLE
Control Panel broken in 4.4.x

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-test-resources#615]
### Expected Behavior

Should work

### Actual Behaviour

Fails with

```
[test-resources-service] 13:46:34.760 [io-executor-thread-1] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error encoding object [Model[categories=[Category[id=main, name=Dashboard, iconClass=fa-tachometer-alt, order=-2147483648]], applicationName=test-resources-server, activeEnvironments=[test], contentView=INDEX, canRefresh=false, canStop=false, ext={currentCategory=Category[id=main, name=Dashboard, iconClass=fa-tachometer-alt, order=-2147483648], controlPanels=[io.micronaut.testresources.controlpanel.DockerHealthControlPanel@f985346, io.micronaut.testresources.controlpanel.TestResourcesControlPanel@19a2c91a, io.micronaut.testresources.controlpanel.TestResourcesControlPanel@421cf237]}]] to JSON: No serializable introspection present for type Model. Consider adding Serdeable. Serializable annotate to type Model. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(Model.class) to enable serialization of this type.
io.micronaut.http.codec.CodecException: Error encoding object [Model[categories=[Category[id=main, name=Dashboard, iconClass=fa-tachometer-alt, order=-2147483648]], applicationName=test-resources-server, activeEnvironments=[test], contentView=INDEX, canRefresh=false, canStop=false, ext={currentCategory=Category[id=main, name=Dashboard, iconClass=fa-tachometer-alt, order=-2147483648], controlPanels=[io.micronaut.testresources.controlpanel.DockerHealthControlPanel@f985346, io.micronaut.testresources.controlpanel.TestResourcesControlPanel@19a2c91a, io.micronaut.testresources.controlpanel.TestResourcesControlPanel@421cf237]}]] to JSON: No serializable introspection present for type Model. Consider adding Serdeable. Serializable annotate to type Model. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(Model.class) to enable serialization of this type.
        at io.micronaut.http.netty.body.NettyJsonHandler.writeTo(NettyJsonHandler.java:164)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.writeNettyMessageBody(RoutingInBoundHandler.java:374)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeHttpResponse(RoutingInBoundHandler.java:353)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.writeResponse(RoutingInBoundHandler.java:247)
        at io.micronaut.http.server.netty.NettyRequestLifecycle.lambda$handleNormal$0(NettyRequestLifecycle.java:94)
        at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl$1.onComplete(ReactorExecutionFlowImpl.java:121)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:159)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
        at io.micronaut.core.async.propagation.ReactivePropagation$2.onNext(ReactivePropagation.java:106)
        at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2812)
        at reactor.core.publisher.SinkOneMulticast.tryEmitValue(SinkOneMulticast.java:66)
        at reactor.core.publisher.SinkOneSerialized.tryEmitValue(SinkOneSerialized.java:38)
        at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl$2.accept(ReactorExecutionFlowImpl.java:171)
        at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl$2.accept(ReactorExecutionFlowImpl.java:164)
        at io.micronaut.core.execution.ImperativeExecutionFlowImpl.onComplete(ImperativeExecutionFlowImpl.java:132)
        at io.micronaut.core.execution.DelayedExecutionFlowImpl$OnComplete.apply(DelayedExecutionFlowImpl.java:330)
        at io.micronaut.core.execution.DelayedExecutionFlowImpl.work(DelayedExecutionFlowImpl.java:51)
        at io.micronaut.core.execution.DelayedExecutionFlowImpl.complete0(DelayedExecutionFlowImpl.java:64)
        at io.micronaut.core.execution.DelayedExecutionFlowImpl.complete(DelayedExecutionFlowImpl.java:70)
        at io.micronaut.core.execution.ExecutionFlow.lambda$async$0(ExecutionFlow.java:94)
        at io.micronaut.core.execution.ImperativeExecutionFlowImpl.onComplete(ImperativeExecutionFlowImpl.java:132)
        at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
        at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.micronaut.serde.exceptions.SerdeException: No serializable introspection present for type Model. Consider adding Serdeable. Serializable annotate to type Model. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(Model.class) to enable serialization of this type.
        at io.micronaut.serde.support.serializers.RuntimeTypeSerializer.lambda$getSerializer$0(RuntimeTypeSerializer.java:135)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.micronaut.serde.support.serializers.RuntimeTypeSerializer.getSerializer(RuntimeTypeSerializer.java:131)
        at io.micronaut.serde.support.serializers.RuntimeTypeSerializer.serialize(RuntimeTypeSerializer.java:76)
```

### Version

4.4.1

**Comment by sdelamo** [comment]
I think this should be in the control panel module as `Model` is a class in place there https://github.com/micronaut-projects/micronaut-control-panel/blob/1.4.x/control-panel-ui/src/main/java/io/micronaut/controlpanel/ui/Model.java
