### ISSUE TITLE
R2DBC can not use the same MySQL container of Flyway

### ISSUE THREAD

**Issue by linweiyu21** [micronaut-projects/micronaut-test-resources#65]
### Issue description

Here is my configuration:

```yaml
test-resources:
  containers:
    mysql:
      image-name: mysql:8
datasources:
  default:
    db-type: mysql
r2dbc:
  datasources:
    default:
      db-type: mysql
      url: r2dbc:tc:mysql:///test?TC_IMAGE_TAG=8
flyway:
  datasources:
    default:
      db-type: mysql
      enabled: true
      url: jdbc:tc:mysql:8:///test
      baseline-on-migrate: true
```

The testcontainers will start another container after Flyway migration is finished

Log:

```log
19:44:56.876 [Test worker] INFO  o.t.utility.RyukResourceReaper - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
19:44:56.877 [Test worker] INFO  o.testcontainers.DockerClientFactory - Checking the system...
19:44:56.877 [Test worker] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
19:44:56.879 [Test worker] INFO  🐳 [mysql:8] - Creating container for image: mysql:8
19:44:57.161 [Test worker] INFO  🐳 [mysql:8] - Container mysql:8 is starting: e59d231fb6043f7afe2f93af348ead7b9775f1d67bd172940daba0b3878320f0
19:44:57.531 [Test worker] INFO  🐳 [mysql:8] - Waiting for database connection to become available at jdbc:mysql://wingman:49255/test using query 'SELECT 1'
19:45:08.572 [Test worker] INFO  🐳 [mysql:8] - Container is started (JDBC URL: jdbc:mysql://wingman:49255/test)
19:45:08.572 [Test worker] INFO  🐳 [mysql:8] - Container mysql:8 started in PT11.69292S
19:45:08.596 [Test worker] INFO  o.f.c.i.d.base.BaseDatabaseType - Database: jdbc:mysql://wingman:49255/test (MySQL 8.0)
19:45:08.691 [Test worker] INFO  o.f.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.035s)
19:45:08.743 [Test worker] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Creating Schema History table `test`.`flyway_schema_history` ...
19:45:08.827 [Test worker] INFO  o.f.core.internal.command.DbMigrate - Current version of schema `test`: << Empty Schema >>
19:45:08.833 [Test worker] INFO  o.f.core.internal.command.DbMigrate - Migrating schema `test` to version "1.0.0 - create robot"
19:45:08.890 [Test worker] INFO  o.f.core.internal.command.DbMigrate - Successfully applied 1 migration to schema `test`, now at version v1.0.0 (execution time 00:00.068s)
19:45:09.533 [testcontainers-r2dbc-0] INFO  🐳 [mysql:8] - Creating container for image: mysql:8
19:45:09.687 [testcontainers-r2dbc-0] INFO  🐳 [mysql:8] - Container mysql:8 is starting: 3439720017e448b1c4f730999b8e8eeba4a7b717f5dda1c7819a57b1b16de078
19:45:09.991 [testcontainers-r2dbc-0] INFO  🐳 [mysql:8] - Waiting for database connection to become available at jdbc:mysql://wingman:49256/test using query 'SELECT 1'
19:45:20.920 [testcontainers-r2dbc-0] INFO  🐳 [mysql:8] - Container is started (JDBC URL: jdbc:mysql://wingman:49256/test)
19:45:20.921 [testcontainers-r2dbc-0] INFO  🐳 [mysql:8] - Container mysql:8 started in PT11.38907S
```

Thanks!

**Comment by melix** [comment]
You need to _remove_ the URLs from your configuration in order for the test resources to kick in. Can you try with:

```
test-resources:
  containers:
    mysql:
      image-name: mysql:8
datasources:
  default:
    db-type: mysql
r2dbc:
  datasources:
    default:
      db-type: mysql
flyway:
  datasources:
    default:
      db-type: mysql
      enabled: true
      baseline-on-migrate: true
```

?

**Comment by linweiyu21** [comment]
I removed all the URLs and try serval times, and it still does' t work.
Output logs:

```logs
Caused by: java.lang.IllegalStateException: Unable to create a ConnectionFactory for 'ConnectionFactoryOptions{options={}}'. Available drivers: [ mysql ]
	at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:143)
	at io.micronaut.r2dbc.R2dbcConnectionFactoryBean.connectionFactory(R2dbcConnectionFactoryBean.java:68)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2333)
	... 90 more
```

After some debugging, I found the `defaultUrl` in `io.micronaut.r2dbc.DefaultBasicR2dbcProperties#newConnectionFactoryOptionsBuilder` is null.

My project url is [https://github.com/linweiyu21/mn-testcontainers-test](https://github.com/linweiyu21/mn-testcontainers-test)

Thank you for your help!

**Comment by melix** [comment]
There were several issues in your reproducer:

1. it wasn't using `micronaut-test-resources`, so no way it would start containers for you
2. it was adding too many dependencies, probably no harm but I removed them
3. it was missing the JDBC pool, so Flyway wouldn't be invoked
4. the database configuration can live in the main application.yml file, simplifying configuration

See https://github.com/linweiyu21/mn-testcontainers-test/pull/1

**Comment by linweiyu21** [comment]
> There were several issues in your reproducer:
> 
> 1. it wasn't using `micronaut-test-resources`, so no way it would start containers for you
> 2. it was adding too many dependencies, probably no harm but I removed them
> 3. it was missing the JDBC pool, so Flyway wouldn't be invoked
> 4. the database configuration can live in the main application.yml file, simplifying configuration
> 
> See [linweiyu21/mn-testcontainers-test#1](https://github.com/linweiyu21/mn-testcontainers-test/pull/1)

Thank you so much!
