### ISSUE TITLE
NullPointerException in TestResourcesPropertiesFactory when Gradle plugin testResources.enabled=false

### ISSUE THREAD

**Issue by noeliajimenezg** [micronaut-projects/micronaut-test-resources#651]
### Expected Behavior

Running my project successfully without running test-resources

### Actual Behaviour

Tests are failing giving this error

```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "io.micronaut.testresources.client.TestResourcesClient.getRequiredProperties(String)" is null
	at io.micronaut.test.extensions.testresources.TestResourcesPropertiesFactory$TestResourcesTestPropertyProvider$1.resolveProperty(TestResourcesPropertiesFactory.java:89)
	at io.micronaut.test.extensions.testresources.TestResourcesPropertiesFactory$TestResourcesTestPropertyProvider$1.<init>(TestResourcesPropertiesFactory.java:85)
	at io.micronaut.test.extensions.testresources.TestResourcesPropertiesFactory$TestResourcesTestPropertyProvider.lambda$extractAnnotationProperties$2(TestResourcesPropertiesFactory.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.micronaut.test.extensions.testresources.TestResourcesPropertiesFactory$TestResourcesTestPropertyProvider.extractAnnotationProperties(TestResourcesPropertiesFactory.java:100)
	at io.micronaut.test.extensions.testresources.TestResourcesPropertiesFactory$TestResourcesTestPropertyProvider.getProperties(TestResourcesPropertiesFactory.java:63)
	at io.micronaut.test.support.TestPropertyProvider.get(TestPropertyProvider.java:34)
	at io.micronaut.test.extensions.AbstractMicronautExtension.loadPropertySourcesFromServicesLoaders(AbstractMicronautExtension.java:392)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:335)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

The NPE is thrown because of this code where stream is called on a null.

```
var props = client.getRequiredProperties(v)
    .stream()
```
https://github.com/micronaut-projects/micronaut-test-resources/blob/066f53dbe6a33b483d62153061ce61edf6e6e1e8/test-resources-extensions/test-resources-extensions-core/src/main/java/io/micronaut/test/extensions/testresources/TestResourcesPropertiesFactory.java#L88

### Steps To Reproduce

grade build -Pmicronaut.testResources=false

### Environment Information

Mac OS

### Example Application

https://github.com/noeliajimenezg/micronaut_error_testresources

### Version

4.5.0

**Comment by melix** [comment]
I wonder if it's related to running on Mac OS. If I clone this project and run:

`gradle test -Pmicronaut.testResources=true`

tests pass as expected, but I'm on Linux. Could you share more logs?

**Comment by noeliajimenezg** [comment]
The issue shows up when you made use of the configuration "enabled=false" from Gradle plugin micronaut-test-resources that I set by using -Pmicronaut.testResources=false.
I suspect the NPE of client returns can be related to this behaviour of the plugin where it excludes the dependency micronaut-test-resources-client.

https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/2b60266a8fcb979b289e447717a2e5b10e48400c/test-resources-plugin/src/main/java/io/micronaut/gradle/testresources/MicronautTestResourcesPlugin.java#L90

**Comment by melix** [comment]
If I use `-Pmicronaut.testResources=false`, the error I get is:

```
Caused by: io.micronaut.context.exceptions.ConfigurationException: Error configuring data source 'default'. No URL specified
        at io.micronaut.jdbc.CalculatedSettings.getUrl(CalculatedSettings.java:109)
        at io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration.getUrl(DatasourceConfiguration.java:94)
        at io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration.postConstruct(DatasourceConfiguration.java:66)
        at io.micronaut.configuration.jdbc.hikari.$DatasourceConfiguration$Definition.initialize(Unknown Source)
        at io.micronaut.configuration.jdbc.hikari.$DatasourceConfiguration$Definition.doInstantiate(Unknown Source)
        at io.micronaut.context.AbstractInitializableBeanDefinition.instantiate(AbstractInitializableBeanDefinition.java:770)
        at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:156)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2327)
        ... 29 common frames omitted
```

which is expected, because the test resources service doesn't kick in. The client shouldn't be added to the application classpath if test resources are disabled. It's quite curious that you get this error :thinking: Would it be possible that you have an init script in `~/.gradle` which would change the configuration?

**Comment by noeliajimenezg** [comment]
I'm not able to get your failure. I don't have anything customised in ~/.gradle.
I tried running Gradle 8.8 and 8.6 (sdkman installed) from my terminal and also the Gradle from IntelliJ.
Have you checked that your .micronaut folder is empty before running the command?
These are screenshots from my debug
<img width="1070" alt="LazyTestResourcesClient" src="https://github.com/micronaut-projects/micronaut-test-resources/assets/37051537/3bdbffbc-b59b-4cd8-89df-ab9fb94b97a0">
<img width="1188" alt="TestResourcesClientHolder" src="https://github.com/micronaut-projects/micronaut-test-resources/assets/37051537/9f9da1d1-defc-4ed0-a77a-2c4d06e62627">

**Comment by melix** [comment]
Ok that's interesting. After I used a new gradle home I get the same error. Now that I can reproduce it's going to be easier to figure out. Thanks for the additional feedback!

**Comment by melix** [comment]
Alright the answer was right under my eyes, you have:

```
    testRuntimeOnly("io.micronaut.testresources:micronaut-test-resources-client:2.5.2")
```

I'm not sure why this is added, but this shouldn't : the client should only be added if test resources are enabled (the plugin adds it automatically based on the value of the flag)

**Comment by noeliajimenezg** [comment]
Thanks a lot for your support!
Unfortunately, the NPE persists even removing that dependency or by using different JDKs or running `./gradlew build -Pmicronaut.testResources=false`.
Not sure how I can give you more hints to reproduce it.

**Comment by melix** [comment]
Right, running `gradle -Pmicronaut.testResources=false dependencyInsight --configuration testRuntimeClasspath --dependency test-resources-client` shows where the client comes from. It's coming from the test resources extensions. So basically you'll need to exclude the client if test resources is disabled. You can do something like this:

```
configurations.all {
   incoming.beforeResolve {
      if (!micronaut.testResources.enabled.get()) {
          exclude module: 'micronaut-test-resources-client'
      }
   }
}
```

I guess it makes sense to make the client a `compileOnly` dependency in the extensions.

(edit: actually this won't work either since you're likely to hit a ClassNotFoundException when running the tests, because of the presence of the extension, so I need a better solution to this)

**Comment by noeliajimenezg** [comment]
Thanks a lot for this fix @melix ! ❤️ 
Waiting for the release! 🚀
